require('mini.cursorword').setup ({})
require('mini.surround').setup ({})
require('mini.tabline').setup ({})
require('mini.comment').setup ({})
-- require('mini.completion').setup ({})
require('mini.indentscope').setup ({})
require('mini.pairs').setup ({})
require('mini.statusline').setup ({})
